import {dimensions,countryCodes,samples} from './data.mjs';
import {rank} from './search.mjs';
const $=id=>document.getElementById(id), names=new Intl.DisplayNames(['nl'],{type:'region'}), money=n=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
let saved={}; try {saved=JSON.parse(localStorage.getItem('vakantiekompas')||'{}')||{};}catch{}
let visited=new Set(Array.isArray(saved.visited)?saved.visited.filter(x=>countryCodes.includes(x)):[]);
for(const id of ['region','people','budget','minTemp','maxTemp']) if(saved[id]!=null) $(id).value=saved[id];
for(const [key,label] of Object.entries(dimensions)) {const wrapper=document.createElement('label');wrapper.className='slider';wrapper.innerHTML=`<span>${label}<output id="out-${key}"></output></span><input type="range" min="0" max="10" value="${Math.min(10,Math.max(0,Number(saved.weights?.[key]??5)||0))}" id="weight-${key}">`; $('sliders').append(wrapper);const input=$('weight-'+key);input.addEventListener('input',()=>{$('out-'+key).value=input.value;});$('out-'+key).value=input.value;}
function countries(){const query=$('countrySearch').value.toLocaleLowerCase('nl');$('countries').replaceChildren();countryCodes.map(code=>({code,name:names.of(code)})).sort((a,b)=>a.name.localeCompare(b.name,'nl')).filter(d=>d.name.toLocaleLowerCase('nl').includes(query)).forEach(d=>{const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.checked=visited.has(d.code);input.addEventListener('change',()=>{input.checked?visited.add(d.code):visited.delete(d.code);store();$('visitedCount').textContent=`${visited.size} landen en gebieden uitgesloten`;});label.append(input,document.createTextNode(d.name));$('countries').append(label);});$('visitedCount').textContent=`${visited.size} landen en gebieden uitgesloten`;}
function filters(){return {region:$('region').value,people:Number($('people').value),budget:Number($('budget').value),minTemp:Number($('minTemp').value),maxTemp:Number($('maxTemp').value),visited:[...visited],weights:Object.fromEntries(Object.keys(dimensions).map(k=>[k,Number($('weight-'+k).value)]))};}
function store(){try{localStorage.setItem('vakantiekompas',JSON.stringify(filters()));}catch{}}
function details(d){$('detailBody').innerHTML=`<p class="eyebrow">VOORBEELDPROFIEL · ${d.region}</p><h2>${names.of(d.code)}</h2><p>Deze gegevens dienen om de zoekervaring te demonstreren. Ze hebben geen bron of actualisatiedatum.</p><h3>Klimaatvoorbeeld</h3><p>${d.temp} °C · ${d.rain} regendagen per maand · ${d.sun} zonuren per dag</p><p>Maandgemiddelden, hoge en lage temperaturen, regenval in mm en beste reisperiode: nog niet beschikbaar.</p><h3>Kostenvoorbeeld</h3><p>${money(d.cost)} verblijf voor 3 weken (voorbeeld voor twee personen); ${money(d.flight)} retourvlucht per persoon. Voor andere groepsgroottes zijn verblijfskosten nog niet aangepast.</p><h3>Ideeën om te verkennen</h3><ul>${d.highlights.map(h=>`<li>${h}</li>`).join('')}</ul><p>Dit zijn vijf ideeën, nog geen geverifieerde top 25.</p><h3>Voor een verstandige keuze</h3><dl><dt>Veiligheid & reisadvies</dt><dd>Nog te koppelen aan actueel officieel reisadvies.</dd><dt>Zelf rijden</dt><dd>Rijbewijsregels, verkeer en lokale omstandigheden nog niet onderzocht.</dd><dt>Regering & staatsvorm</dt><dd>Nog niet beschikbaar; bron en peildatum vereist.</dd></dl><a href="https://www.nederlandwereldwijd.nl/reisadvies" target="_blank" rel="noopener noreferrer">Bekijk officieel Nederlands reisadvies ↗</a>`;$('detail').showModal();}
function search(){if(!$('filters').reportValidity())return;const f=filters();if(f.minTemp>f.maxTemp){$('error').textContent='De minimumtemperatuur moet lager zijn dan de maximumtemperatuur.';return;}$('error').textContent='';store();const results=rank(samples,f);$('count').textContent=`${results.length} bestemmingen`;$('cards').replaceChildren();if(!results.length){$('cards').innerHTML='<div class="panel"><h3>Geen voorbeeldbestemmingen gevonden</h3><p>Verhoog het budget, verruim de temperatuur of kies een andere regio.</p></div>';return;}results.forEach((d,i)=>{const card=document.createElement('article');card.className='card';card.innerHTML=`<div class="cardTop"><span class="region">${d.region} · voorbeeld</span><span class="score">${d.score}% match</span></div><h3><span class="ordinal">${String(i+1).padStart(2,'0')}</span> ${names.of(d.code)}</h3><div class="tags">${d.reasons.map(k=>`<span>${dimensions[k]}</span>`).join('')}</div><div class="facts"><div><strong>${d.temp} °C</strong><small>temperatuurvoorbeeld</small></div><div><strong>${money(d.cost+d.flight*f.people)}</strong><small>3 weken incl. vlucht*</small></div><div><strong>${d.sun} uur</strong><small>zon per dag, voorbeeld</small></div></div><p class="hint">* Vast verblijfsvoorbeeld voor twee; vluchten voor ${f.people} reiziger(s).</p><button class="secondary">Ontdek de mogelijkheden ↗</button>`;card.querySelector('button').addEventListener('click',()=>details(d));$('cards').append(card);});}
$('filters').addEventListener('submit',e=>{e.preventDefault();search();});$('countrySearch').addEventListener('input',countries);$('clearVisited').addEventListener('click',()=>{visited.clear();countries();search();});$('close').addEventListener('click',()=>$('detail').close());$('reset').addEventListener('click',()=>{try{localStorage.removeItem('vakantiekompas');}catch{}location.reload();});countries();search();
