import {cityHighlights} from './city-highlights.mjs';
import {climateData} from './climate-data.mjs';
import {geography,geographySource} from './geography.mjs';
import {travelConcept,daylightHours} from './transport.mjs';
const islandIds=new Set('ID-bali ID-lombok ID-gili-air ID-gili-meno ID-gili-trawangan ID-komodo ID-raja GR-crete GR-rhodes GR-corfu GR-naxos GR-paros GR-santorini US-hawaii-oahu US-hawaii-maui US-hawaii-kauai US-hawaii-big EC-galapagos PH-palawan CK-rarotonga CK-aitutaki SC-mahe SC-praslin SC-la-digue'.split(' '));
const nonHoliday=new Set('AQ BV HM GS TF UM'.split(' '));
const vietnam={
 'VN-north':{natuur:9,cultuur:9,historie:8,steden:4,bossen:8,strand:4,duiken:3,zwemmen:5,zon:5,dieren:6,relax:7,avontuur:9,wandelen:9,roadtrip:8,eten:9,wellness:7,nachtleven:4,levendig:5},
 'VN-central':{natuur:8,cultuur:9,historie:9,steden:5,bossen:8,strand:8,duiken:5,zwemmen:8,zon:6,dieren:5,relax:8,avontuur:8,wandelen:8,roadtrip:8,eten:9,wellness:8,nachtleven:5,levendig:5},
 'VN-south':{natuur:8,cultuur:8,historie:7,steden:5,bossen:7,strand:8,duiken:6,zwemmen:8,zon:6,dieren:6,relax:8,avontuur:7,wandelen:6,roadtrip:6,eten:9,wellness:8,nachtleven:6,levendig:6}
};
export const interestDefinitions={natuur:'Landschappen en natuurbezoek; niet het percentage natuur in een land.',cultuur:'Lokale tradities, kunst, eten en culturele ervaringen.',historie:'Toegankelijke historische plekken en hun verhaal.',steden:'Activiteiten in een stedelijke omgeving; geen verplicht deel van een rondreis.',bossen:'Praktische mogelijkheden om bos of jungle te bezoeken, niet landelijk bosoppervlak.',strand:'Mogelijkheden voor strand en kust in de gekozen regio.',duiken:'Toegankelijke duikmogelijkheden; ervaring en omstandigheden blijven belangrijk.',zwemmen:'Zwemplekken; geen garantie op veilig zwemwater.',zon:'Mogelijkheden voor een vakantie gericht op zonnen; geen gemeten zonuren.',dieren:'Mogelijkheden voor verantwoord wildlife-bezoek.',relax:'Rustige dagen en plekken met weinig geplande activiteiten.',avontuur:'Actieve of uitdagende reiservaringen.',wandelen:'Wandelmogelijkheden passend bij voorbereiding en conditie.',roadtrip:'Geschiktheid van een routeconcept met veel reizen over land.',eten:'Lokale keuken en toegankelijke culinaire ervaringen.',wellness:'Massages, spa’s en behandelingen; niet automatisch luxe wellnessretreats.',nachtleven:'Avondactiviteiten en uitgaan.',levendig:'Drukke, levendige plekken. Gewicht 0 betekent niet belangrijk, geen uitsluiting.'};
const citySpecs=[['VN-hanoi','VN-north','Hanoi'],['VN-hoian','VN-central','Hội An'],['VN-saigon','VN-south','Ho Chi Minhstad'],['AR-buenos-city','AR-buenos','Buenos Aires'],['BR-rio-city','BR-southeast','Rio de Janeiro'],['CO-bogota','CO','Bogotá'],['CO-cartagena','CO','Cartagena'],['GY-georgetown','GY','Georgetown'],['ST-city','ST','São Tomé-stad'],['US-newyork','US-east','New York'],['US-washington','US-east','Washington D.C.'],['CA-montreal','CA-east','Montréal'],['JP-tokyo','JP','Tokio'],['JP-kyoto','JP','Kyoto'],['TH-bangkok','TH','Bangkok'],['PT-lisbon','PT','Lissabon'],['ES-barcelona','ES','Barcelona'],['FR-paris','FR','Parijs'],['IT-rome','IT','Rome']];
function blankMonths(lat){return Array.from({length:12},(_,i)=>({temp:null,low:null,high:null,rain:null,sun:null,daylight:daylightHours(lat,i+1)}));}
function normalize(d){
 const fact=geography[d.code];const transport=travelConcept(d),lat=transport?.airport.lat??fact.lat;
 const reviewed=vietnam[d.id];
 return {...d,type:islandIds.has(d.id)?'island':d.id===d.code?'country':'region',parentId:d.id===d.code?null:d.code,catalogOnly:false,
  scores:reviewed|| (d.basis==='uitgewerkt'?d.scores:{}),scoreStatus:reviewed?'editorial':d.basis==='uitgewerkt'?'example':'unknown',
  scoreNotes:reviewed?{bossen:'Noordelijke bergbossen en natuurgebieden; midden-Vietnam bevat onder meer Phong Nha. Regio’s verschillen en beschermde natuur vraagt voorbereiding.',steden:'Stadsbezoek is mogelijk, maar geen verplicht zwaartepunt. Kies een rondreis of vermijd losse stedentrips.',wellness:'Massages en spa’s zijn gangbaar in reisplaatsen; kwaliteit en aanbod verschillen. Dit beoordeelt geen luxe retreatkwaliteit.',zon:'Dit is een redactionele inschatting van strand-/zonvakantiemogelijkheden. Vietnam heeft regionale regenseizoenen; altijd zonnig wordt niet geclaimd.'}:{},
  climate:blankMonths(lat),climateStatus:'unknown',climateReference:transport?.airport.city||'indicatieve landcoördinaat',bestMonths:null,
  transport,geography:fact,children:[],description:d.code==='GY'?'Guyana ligt op het Zuid-Amerikaanse vasteland. Regenwoud, rivieren en wildlife zijn belangrijker voor een natuurreis dan een kleine strandvakantie.':d.code==='ST'?'São Tomé en Príncipe is een vulkanische eilandstaat met regenwoud, oude cacao-roças, bergen en stranden. Het is geen verzameling kleine zandatollen.':d.description,
  styles:reviewed?['roundtrip','active','relax',...(d.id!=='VN-north'?['beach']:[])]:d.styles
 };
}
export function completeCatalog(codes,legacy,names){
 const records=legacy.map(normalize);
 const lombok=records.find(d=>d.id==='ID-lombok');lombok.name='Lombok';lombok.description='Lombok: Rinjani, dorpen, watervallen en zuidelijke stranden. De Gili-eilanden zijn aparte bestemmingen met een boottransfer.';lombok.highlights=lombok.highlights.filter(h=>!h.name.startsWith('Gili '));
 const flores=records.find(d=>d.id==='ID-flores');flores.name='Flores';flores.highlights=flores.highlights.filter(h=>!['Komodo nationaal park','Rinca','Padar','Pink Beach','Kelor'].includes(h.name));
 for(const [id,name] of [['ID-gili-air','Gili Air'],['ID-gili-meno','Gili Meno'],['ID-gili-trawangan','Gili Trawangan'],['ID-komodo','Komodo & Rinca']]){const base=id==='ID-komodo'?legacy.find(d=>d.id==='ID-flores'):legacy.find(d=>d.id==='ID-lombok');records.push(normalize({...base,id,name,highlights:base.highlights.filter(h=>id==='ID-komodo'?['Komodo nationaal park','Rinca','Padar','Pink Beach'].includes(h.name):h.name===name),description:id==='ID-komodo'?'Vulkanische eilanden met varanen en mariene natuur. De gebruikelijke excursieroute vereist lange boottrajecten.':`${name} is bereikbaar via Lombok en een aparte boottransfer. Kies de route bewust als je zeeziek bent.`}));}
 for(const [id,parentId,name] of citySpecs){const parent=records.find(d=>d.id===parentId);if(!parent)continue;const scores={natuur:4,cultuur:9,historie:8,steden:10,bossen:2,strand:2,duiken:1,zwemmen:3,zon:3,dieren:2,relax:5,avontuur:4,wandelen:6,roadtrip:2,eten:9,wellness:7,nachtleven:8,levendig:9};records.push({...parent,id,name,type:'city',parentId,children:[],styles:['city'],scores,scoreStatus:'editorial',scoreNotes:{steden:'Dit profiel is een stedentrip, niet een complete rondreis door het land.'},highlights:cityHighlights[id],description:`${name}: een stadsgerichte reis. Kies het land- of regioprofiel voor een afwisselende rondreis; deze scores zijn redactionele richtlijnen.`,transport:travelConcept({...parent,id})});}
 for(const code of codes){if(records.some(d=>d.id===code))continue;const fact=geography[code],children=records.filter(d=>d.code===code);records.push({id:code,code,name:names.of(code),region:fact.region,type:'country',parentId:null,description:`${names.of(code)}: ${fact.subregion || fact.region}. ${fact.capital.length?'Hoofdplaats: '+fact.capital.join(', ')+'. ':''}${fact.landlocked?'Dit gebied heeft geen zeekust. ':''}Specifieke vakantieprofielen en actuele reisgegevens zijn nog niet uitgewerkt.`,basis:'catalogus',highlights:[],scores:{},scoreStatus:'unknown',scoreNotes:{},pricing:null,styles:[],bestMonths:null,climate:blankMonths(fact.lat),climateStatus:'unknown',climateReference:'indicatieve landcoördinaat',transport:children.length?null:travelConcept({id:code,code}),geography:fact,children:[],catalogOnly:children.length>0||nonHoliday.has(code),driving:'Nog niet gecontroleerd.'});}
 for(const d of records){if(d.type==='city'){d.climateReference=d.transport?.airport.city||d.name;d.climate=blankMonths(d.transport?.airport.lat||d.geography.lat);}if(climateData[d.id]){d.climate=climateData[d.id].months.map((m,i)=>({...m,daylight:d.climate[i].daylight}));d.climateStatus='reanalysis';d.climateSource=climateData[d.id].source;d.climateReference=climateData[d.id].reference;d.bestMonths=d.climate.flatMap((m,i)=>Number.isFinite(m.temp)&&Number.isFinite(m.rain)&&Number.isFinite(m.sun)&&m.temp>=18&&m.temp<=32&&m.rain<=150&&m.sun>=5?[i+1]:[]);}d.children=records.filter(child=>child.parentId===d.id).map(child=>child.id);if(d.type==='country')d.catalogOnly=nonHoliday.has(d.code)||records.some(child=>child.parentId===d.id&&child.type!=='city');d.climateSource??=null;d.highlights=d.highlights.map(h=>({...h,boatActivity:/boot|rivierexpeditie|eilandexcursie/i.test(h.name+' '+h.description)}));}
 return records;
}
export {geographySource};
