// Destination-specific editorial ideas. Numeric values are planning templates.
const make=(id,code,name,kind,season,places)=>({id,code,name,kind,season,highlights:places.split('|').map(s=>{const [name,description]=s.split('~');return {name,description,kind:'Highlight'};})});
export const regionalCatalog = [
make('US-hawaii-oahu','US','Hawaii · Oahu','island','winterTropics','Honolulu~Stad met musea, lokale keuken en eilandleven.|Waikiki~Bekende strandwijk met voorzieningen en surfcultuur.|Pearl Harbor~Historische locaties over de Tweede Wereldoorlog.|North Shore~Noordelijke kust met seizoensgebonden grote golven.|Diamond Head~Vulkanische krater met gereguleerde wandelroute en stadszicht.'),
make('US-hawaii-maui','US','Hawaii · Maui','island','winterTropics','Haleakalā~Vulkanisch berglandschap; toegang en zonsopkomstbezoek vooraf plannen.|Road to Hāna~Kustroute met groene valleien en bochtige wegen.|ʻĪao Valley~Groene vallei met culturele betekenis en wandelmogelijkheden.|Kīhei~Kustplaats als uitvalsbasis voor stranden.|Upcountry Maui~Hooggelegen dorpen en landbouwgebieden; controleer actuele lokale omstandigheden.'),
make('US-hawaii-kauai','US','Hawaii · Kauai','mountain','winterTropics','Waimea Canyon~Diepe kloof met kleurrijke erosielandschappen.|Nā Pali Coast~Steile kust met gereguleerde boot- en wandeltoegang.|Hanalei~Baai en dorp in een groene noordelijke omgeving.|Poʻipū~Zuidelijke kust met stranden.|Wailua~Rivierlandschap met culturele locaties en watervallen.'),
make('US-hawaii-big','US','Hawaii · Big Island','island','winterTropics','Hawaiʻi Volcanoes~Vulkanisch park met wisselende activiteit; volg actuele veiligheidsregels.|Kona~Westelijke kustplaats met koffiegebieden in de omgeving.|Hilo~Groenere oostelijke stad met lokale markten.|Akaka Falls~Waterval in een tropische bosomgeving.|Puʻuhonua o Hōnaunau~Historische plek om Hawaïaanse cultuur met context te leren kennen.'),
make('EC-mainland','EC','Ecuador · vasteland','mountain','highland','Quito~Historische stad in de Andes met musea en pleinen.|Cotopaxi~Vulkanisch berglandschap; hoogte en toegangsstatus zijn belangrijk.|Cuenca~Historische stad met koloniale architectuur en lokale ambachten.|Otavalo~Plaats bekend om markttradities en omliggende hooglandcultuur.|Mindo~Nevelwoudgebied voor vogels, natuurwandelingen en lokale excursies.'),
make('EC-galapagos','EC','Galápagoseilanden','island','equatorial','Santa Cruz~Eiland met onderzoeks- en bezoekerslocaties en reuzenschildpadden.|Isabela~Vulkanisch eiland met kustnatuur en gereguleerde excursies.|San Cristóbal~Eiland met lokale dorpen en bijzondere wildlifeplekken.|Tortuga Bay~Strandgebied waar natuurregels en gemarkeerde toegang belangrijk zijn.|Begeleide eilandexcursie~Ontdek endemische soorten via vergunninghouders; route en toegang verschillen.'),
make('VN-north','VN','Vietnam · noorden','culture','temperate','Hanoi~Historische straten, streetfood en stadsleven rond meren.|Ninh Binh~Kalksteenlandschap met rivier- en fietsroutes.|Ha Long~Karstbaaien te bezoeken met verantwoord gekozen boottochten.|Sapa~Berglandschap en dorpen; respecteer lokale gemeenschappen.|Hà Giang~Bergregio voor goed voorbereide routes met passende begeleiding.'),
make('VN-central','VN','Vietnam · midden','culture','winterTropics','Hội An~Historische handelsstad met ambachten en lokale keuken.|Huế~Voormalige keizerlijke stad met paleizen en graven.|Đà Nẵng~Kuststad met stranden en toegang tot omliggende plaatsen.|Mỹ Sơn~Archeologisch tempelcomplex van de Cham.|Phong Nha~Karstgebied met grotten en gereguleerde natuurtochten.'),
make('VN-south','VN','Vietnam · zuiden','mixed','winterTropics','Ho Chi Minhstad~Metropool met historische musea en levendige eetstraten.|Mekongdelta~Rivierlandschap met dorpen, markten en landbouw.|Cần Thơ~Uitvalsbasis voor rivier- en marktbezoek.|Phú Quốc~Eiland met kustgebieden en strandsfeer.|Côn Đảo~Eilandengroep met natuur en belangrijke historische context.'),
make('AR-patagonia','AR','Argentinië · Patagonië','mountain','southern','El Chaltén~Bergdorp en startpunt voor wandelroutes bij Fitz Roy.|Perito Moreno~Gletsjer met uitzichtpaden; excursieregels vooraf controleren.|Ushuaia~Zuidelijke havenstad bij berg- en kanaallandschappen.|Bariloche~Merengebied met bergen en seizoensgebonden buitenactiviteiten.|Península Valdés~Kustgebied met seizoensgebonden wildlife; bezoekkalender controleren.'),
make('AR-north','AR','Argentinië · noordwesten','culture','southern','Salta~Historische stad met musea en lokale eettradities.|Quebrada de Humahuaca~Kleurrijke bergvallei met dorpen en cultuur.|Purmamarca~Dorp bij een karakteristieke meerkleurige berghelling.|Cafayate~Wijnregio met droge rotslandschappen.|Salinas Grandes~Hooggelegen zoutvlakte; hoogte en route zorgvuldig plannen.'),
make('AR-buenos','AR','Buenos Aires & omgeving','city','southern','San Telmo~Historische wijk met markten en tangocultuur.|Recoleta~Stadswijk met architectuur en historische begraafplaats.|Palermo~Groene stadsgebieden, horeca en hedendaagse cultuur.|Teatro Colón~Historisch theater met bijzondere architectuur.|Tigre~Rivierdelta dichtbij de stad voor een dagtocht.'),
make('BR-southeast','BR','Brazilië · Rio & zuidoosten','culture','southern','Rio de Janeiro~Stad tussen bergen en zee met bekende cultuurwijken.|Suikerbroodberg~Uitzichtpunt op baai, kust en stad.|Tijuca~Bosrijk parkgebied binnen het stedelijk landschap.|Paraty~Historische kustplaats met oude straten.|Ilha Grande~Bosrijk eiland met stranden en wandelroutes.'),
make('BR-amazon','BR','Brazilië · Amazone','jungle','equatorial','Manaus~Rivierstad en logistieke uitvalsbasis voor het Amazonegebied.|Meeting of Waters~Plek waar verschillende rivieren zichtbaar samenkomen.|Anavilhanas~Riviereilanden en boslandschappen.|Begeleide rivierexpeditie~Leer over natuur en lokale gemeenschappen met passende begeleiding.|Bosverblijf~Een kleinschalige natuurervaring waarbij toegang, vervoer en aanbieder belangrijk zijn.'),
make('BR-northeast','BR','Brazilië · noordoosten','island','tropical','Salvador~Historische stad met Afro-Braziliaanse cultuur en muziek.|Lençóis Maranhenses~Duinenlandschap met seizoensgebonden zoetwaterlagunes.|Olinda~Historische stad met kunst en kleurrijke bebouwing.|Jericoacoara~Kustplaats met duinen en windafhankelijke buitenactiviteiten.|Recife~Havenstad met musea, wijken en lokale tradities.'),
make('PH-palawan','PH','Filipijnen · Palawan','island','winterTropics','El Nido~Kalksteenbaaien en eilanden voor begeleide boottochten.|Coron~Meren, kustlandschap en wrakduiken voor passende ervaring.|Puerto Princesa~Uitvalsbasis voor de gereguleerde ondergrondse rivier.|Port Barton~Kleinschaliger kustplaats met eilanden in de omgeving.|Snorkelexcursie~Verken mariene natuur met een verantwoord gekozen lokale aanbieder.'),
make('PH-visayas','PH','Filipijnen · Cebu & Bohol','island','winterTropics','Chocolate Hills~Karakteristieke heuvels op Bohol met seizoensgebonden kleur.|Cebu City~Historische stad met lokale cultuur en voedseltradities.|Moalboal~Kustplaats met mariene natuur; respecteer wildlifeafstand.|Panglao~Eiland met stranden en duikmogelijkheden.|Loboc~Riviergebied met dorpen en binnenlandse landschappen.'),
make('PH-luzon','PH','Filipijnen · Luzon','culture','winterTropics','Intramuros~Ommuurde historische wijk van Manila.|Banaue~Berggebied met traditionele rijstterrassen.|Batad~Amfitheaterachtige terrassen met wandeltoegang.|Vigan~Historische stad met koloniale straten.|Baguio~Hooglandstad met markten en toegang tot berggebieden.'),
make('CK-rarotonga','CK','Cookeilanden · Rarotonga','island','islandSouth','Muri Lagoon~Lagunegebied voor rustige watersport en strandbezoek.|Avarua~Hoofdplaats met markt en eilandcultuur.|Te Rua Manga~Berglandschap met begeleid te plannen wandelroutes.|Culturele avond~Muziek, dans en lokale gerechten met culturele context.|Rondje eiland~Ontdek dorpen en kustgebieden zonder een ingewikkelde reisroute.'),
make('CK-aitutaki','CK','Cookeilanden · Aitutaki','island','islandSouth','Aitutaki Lagoon~Ondiepe lagune met kleine eilandjes en mariene landschappen.|Arutanga~Dorpsomgeving met eilandleven en lokale historie.|One Foot Island~Klein eiland in de lagune voor georganiseerde dagtochten.|Snorkeltocht~Ontdek rifnatuur met aandacht voor lokale regels en omstandigheden.|Lagunedag~Een rustig reisdeel met tijd voor zwemmen en ontspannen.'),
make('SC-mahe','SC','Seychellen · Mahé','island','islandSouth','Victoria~Kleine hoofdstad met markt en lokale cultuur.|Morne Seychellois~Bergachtig park met bosroutes.|Beau Vallon~Strandbaai met voorzieningen en watersport.|Anse Intendance~Indrukwekkend strand; stroming en zwemcondities vooraf controleren.|Takamaka~Zuidelijk kustgebied met dorpen en strandlandschappen.'),
make('SC-praslin','SC','Seychellen · Praslin','island','islandSouth','Vallée de Mai~Palmwoud met coco-de-mer en bijzondere biodiversiteit.|Anse Lazio~Baai met zandstrand en granieten rotsen.|Anse Georgette~Strand met toegang die vooraf gepland moet worden.|Curieuse~Nabijgelegen eiland met natuur en reuzenschildpadden.|Côte d’Or~Kustgebied als uitvalsbasis voor lokale excursies.'),
make('SC-la-digue','SC','Seychellen · La Digue','island','islandSouth','Anse Source d’Argent~Granieten rotsformaties langs ondiepe strandbaaien.|La Passe~Klein dorp met haven en eilandleven.|Grand Anse~Ruwe kust met indrukwekkende stranden; zwemcondities controleren.|Union Estate~Historisch terrein met landbouw- en eilandgeschiedenis.|Fietsrondje eiland~Verken dorpen en rustige kustwegen op een langzaam tempo.')
];
