import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {searchDestinations,priceTrip,relaxedFilters,preferenceFit,evaluateDestination,selectedMonths,excluded} from '../search.mjs';
import {destinations,countryCodes,coverage} from '../data.mjs';
import {climateData} from '../climate-data.mjs';
import {heritageSites,researchSources} from '../heritage-data.mjs';
import {daylightHours,distanceKm,travelConcept} from '../transport.mjs';
import {profileFromGeography} from '../catalog-model.mjs';
import {regionalHeritage} from '../regional-heritage.mjs';
import {heritageNotes} from '../heritage-notes.mjs';
import {migrateState} from '../state.mjs';
const defaults={visited:[],visitedRegions:[],region:'',budget:3000,people:4,days:21,months:[7],monthMode:'any',styles:[],weights:{natuur:10,bossen:8,cultuur:5},unknownPolicy:'include',tripPace:'balanced'};
const get=id=>destinations.find(d=>d.id===id);
const search=f=>searchDestinations(destinations,{...defaults,...f});
test('all 249 ISO entries and expanded profiles have consistent parents and no duplicate IDs',()=>{assert.equal(coverage.countries,249);assert.ok(coverage.cities>=350);assert.ok(coverage.regional>=140);assert.equal(new Set(destinations.map(d=>d.id)).size,destinations.length);for(const code of countryCodes)assert.ok(get(code));for(const d of destinations){assert.ok(countryCodes.includes(d.code));assert.ok(d.region);if(d.parentId)assert.ok(get(d.parentId));assert.equal(d.climate.length,12);assert.ok(d.children.every(id=>get(id).parentId===d.id));}});
test('no automatically generated prices, flight times, boat durations or offer scores remain',()=>{for(const d of destinations){assert.equal(d.pricing,null);assert.equal(d.transport,null);assert.deepEqual(d.scores,{});assert.equal(priceTrip(d,defaults),null);}assert.equal(travelConcept(get('VG')),null);});
test('all highlights trace to factual UNESCO records and a dated historical mirror',()=>{assert.equal(heritageSites.length,1223);assert.equal(researchSources.heritage_xls.period,'2024');for(const d of destinations)for(const h of d.highlights){assert.ok(h.url.startsWith('https://whc.unesco.org/en/list/'));assert.ok(h.description.length>40);assert.equal(h.source.period,'2024');assert.ok(!h.name.includes('<'));}});
test('local highlights respect country and explicit geographical radius',()=>{for(const d of destinations.filter(d=>d.type!=='country'&&!Object.hasOwn(regionalHeritage,d.id)))for(const h of d.highlights){const site=heritageSites.find(s=>h.url===s.url);assert.ok(site.codes.includes(d.code));assert.ok(distanceKm(d.climatePoint,site)<=(d.type==='city'?60:180)+.001);}});
test('Java has specific sourced temple highlights rather than a generic country template',()=>{const d=get('ID-java');assert.ok(d.highlights.some(h=>h.name.includes('Borobudur')));assert.ok(d.highlights.some(h=>h.name.includes('Prambanan')));assert.ok(!d.description.includes('sjabloon'));assert.ok(d.highlights.find(h=>h.name.includes('Borobudur')).description.includes('stoepa'));});
test('unknown dimensions and weather never become zero or silently disappear',()=>{const d={...get('AD'),climate:get('AD').climate.map(c=>({...c,sun:null}))};assert.equal(d.climate[0].sun,null);const e=evaluateDestination(d,{...defaults,minSun:5,maxTravelHours:10,maxBoatMinutes:30});assert.equal(e.status,'unknown');assert.ok(e.unknown.includes('minSun'));assert.ok(e.unknown.includes('budget'));assert.ok(e.unknown.includes('maxTravelHours'));assert.equal(e.score,null);assert.ok(searchDestinations([d],{...defaults,minSun:5}).recommendations.some(x=>x.id==='AD'));});
test('unknown policy is optional; confirmed failures remain separate',()=>{const a=search({maxTravelHours:1});assert.ok(a.recommendations.length>0);assert.ok(a.recommendations.some(d=>d.status==='unknown'));assert.ok(search({maxTravelHours:1,unknownPolicy:'hide'}).recommendations.every(d=>d.status==='match'));assert.ok(search({maxTravelHours:1,unknownPolicy:'separate'}).uncertain.length>0);});
test('real historical climate has source, period, units and sane monthly values',()=>{assert.ok(coverage.climate>=Object.keys(climateData).filter(id=>get(id)).length);assert.equal(coverage.climateReferences,Object.keys(climateData).filter(id=>get(id)).length);assert.ok(coverage.climate>=37);for(const [id,record] of Object.entries(climateData)){if(!get(id))continue;assert.equal(get(id).climateStatus,'reanalysis');assert.ok(['2015–2024','2001–2020'].includes(record.source.period));for(const m of record.months){assert.ok(m.low<=m.temp&&m.temp<=m.high);assert.ok(m.rain>=0&&(m.sun===null||m.sun>=0&&m.sun<=24));}}assert.notEqual(get('CO-bogota').climate[8].temp,get('CO-cartagena').climate[8].temp);});
test('daylight stays distinct from modeled sunshine',()=>{assert.ok(daylightHours(0,9)>=11.9);assert.ok(daylightHours(52,6)>daylightHours(52,12));assert.notEqual(get('VN-north').climate[8].sun,get('VN-north').climate[8].daylight);});
test('visited Bali also removes Bali administrative detail, leaving Java',()=>{const r=search({visitedRegions:['ID-bali']});assert.ok(!r.recommendations.some(d=>d.id==='ID-bali'||d.id==='ID-admin-1826'));assert.ok(r.recommendations.some(d=>d.id==='ID-java'));assert.ok(!search({visited:['ID']}).recommendations.some(d=>d.code==='ID'));});
test('visited western regions remove their finer administrative descendants',()=>{assert.ok(excluded(get('US-admin-1416'),{visitedRegions:['US-west']},destinations));assert.ok(excluded(get('CA-admin-875'),{visitedRegions:['CA-west']},destinations));assert.ok(!excluded(get('CA-admin-873'),{visitedRegions:['CA-west']},destinations));});
test('excluded countries and trip types remain explainable in search',()=>{for(const code of ['AF','KP','IL'])assert.ok(search({}).evaluated.find(d=>d.id===code).hard.some(x=>x.key==='excludedCountry'));assert.equal(evaluateDestination(get('VN-hanoi'),{...defaults,types:['country','region']}).status,'excluded');});
test('outside Europe correctly uses sourced geographical region',()=>{const r=search({region:'outsideEurope'});assert.ok(r.recommendations.length);assert.ok([...r.recommendations,...r.near].every(d=>d.region!=='Europa'));});
test('direct flight and transfers remain unknown without timetable evidence',()=>{const d=evaluateDestination(get('VG'),{...defaults,directOnly:true,maxStops:1,maxTravelHours:14,maxBoatMinutes:30});assert.equal(d.status,'unknown');for(const k of ['directOnly','maxStops','maxTravelHours','maxBoatMinutes'])assert.ok(d.unknown.includes(k));});
test('sourced route limits exclude known excessive boat or travel times, never relax them',()=>{const base=get('ID-java'),d={...base,transport:{flightMax:13,totalMax:26,stops:2,boat:{maxMinutes:90}}};for(const [key,n] of [['maxTravelHours',20],['maxBoatMinutes',30],['maxStops',1]]){const r=searchDestinations([d],{...defaults,[key]:n});assert.equal(r.evaluated[0].status,'excluded');assert.equal(r.near.length,0);}assert.equal(evaluateDestination(d,{...defaults,directOnly:true}).status,'excluded');});
test('long trips on compact destinations warn without an invented maximum stay',()=>{const sx=evaluateDestination(get('SX'),defaults);assert.ok(sx.itineraryNotes.length);assert.notEqual(sx.status,'excluded');assert.equal(evaluateDestination(get('SX'),{...defaults,days:9}).itineraryNotes.length,0);assert.equal(evaluateDestination(get('SX'),{...defaults,tripPace:'relax'}).itineraryNotes.length,0);assert.equal(evaluateDestination(get('SR'),defaults).itineraryNotes.length,0);});
test('country tours remain available even with many city/regional profiles',()=>{for(const id of ['ID','VN','US','ST','CO'])assert.equal(get(id).catalogOnly,false);assert.ok(search({types:['country']}).recommendations.some(d=>d.id==='VN'));});
test('any/every month use actual individual months rather than an average',()=>{const d={...get('ID-java'),climate:get('ID-java').climate.map((c,i)=>({...c,rain:i===0?300:50}))};const f={...defaults,months:[1,7],maxRain:250};assert.equal(evaluateDestination(d,f).status,'unknown');const every=evaluateDestination(d,{...f,monthMode:'all'});assert.equal(every.status,'near');assert.deepEqual(every.failures[0].months,[1]);assert.equal(relaxedFilters(f,every).maxRain,300);});
test('an unknown weather month does not hide a known passing alternative',()=>{const d={...get('ID-java'),climate:get('ID-java').climate.map((c,i)=>({...c,sun:i===0?null:8}))};assert.ok(!evaluateDestination(d,{...defaults,months:[1,7],minSun:5}).unknown.includes('minSun'));assert.ok(evaluateDestination(d,{...defaults,months:[1,7],monthMode:'all',minSun:5}).unknown.includes('minSun'));});
test('personal scores explain loss and insufficient coverage remains unscored',()=>{const fit=preferenceFit({scores:{natuur:10,cultuur:4}},{natuur:2,cultuur:1});assert.equal(fit.score,80);assert.equal(fit.breakdown.reduce((s,x)=>s+x.loss,0),20);assert.equal(preferenceFit({scores:{natuur:8}},{natuur:5,cultuur:5}).score,null);});
test('source evidence responds to weights without inventing numerical offers',()=>{const d=get('ID-java');const a=evaluateDestination(d,{...defaults,weights:{cultuur:10}}),b=evaluateDestination(d,{...defaults,weights:{wellness:10}});assert.ok(a.relevance>0);assert.equal(b.relevance,0);assert.equal(a.score,null);assert.ok(a.interestEvidence.includes('cultuur'));});
test('full geographical directory can create a sourced ordinary profile',()=>{const index=JSON.parse(readFileSync(new URL('../geographic-index.json',import.meta.url)));assert.ok(index.cities.length>170000&&index.regions.length>5000);const row=index.cities.find(r=>r[1]==='LA'&&r[2].includes('Luang Prabang'));assert.ok(row);const d=profileFromGeography(row,'city',new Intl.DisplayNames(['nl'],{type:'region'}));assert.equal(d.code,'LA');assert.equal(d.parentId,'LA');assert.equal(d.pricing,null);assert.ok(d.profileSource.url.includes('cities.json'));});
test('v5 migration preserves per-person budget, saved places and months',()=>{const old={version:4,budget:3000,selected:['ID-java'],visitedRegions:['ID-bali'],months:[7,9],unknownPolicy:'show'};const a=migrateState(old);assert.equal(a.version,6);assert.equal(a.budget,3000);assert.deepEqual(a.months,[7,9]);assert.deepEqual(a.selected,['ID-java']);assert.equal(a.unknownPolicy,'include');assert.equal(migrateState({budget:6000,people:4}).budget,1500);assert.deepEqual(selectedMonths({months:[7,7,1,99,'3']}),[1,3,7]);assert.equal(search({months:[]}).recommendations.length,0);});

test('regional associations and detailed notes identify the correct actual sites',()=>{assert.equal(heritageSites.find(s=>s.id==='28').name,'Yellowstone National Park');assert.ok(heritageNotes['28'].includes('geisers'));assert.equal(heritageNotes['63'],undefined);assert.ok(get('VN-central').highlights.some(h=>h.url.endsWith('/951/')));assert.ok(get('VN-central').evidence.includes('bossen'));assert.ok(get('ID-java').highlights.some(h=>h.url.endsWith('/608/')));assert.ok(get('CW').highlights.some(h=>h.url.endsWith('/819/')));for(const d of destinations)for(const h of d.highlights)assert.ok(heritageSites.find(s=>s.url===h.url).codes.includes(d.code));});

test('positive evidence for one travel style never falsely rules out another style',()=>{const d=evaluateDestination(get('VN'),{...defaults,styles:['beach']});assert.ok(!d.hard.some(x=>x.key==='styles'));assert.ok(d.unknown.includes('styles'));});
test('optional UNESCO filters check named evidence, not invented activity scores',()=>{assert.equal(evaluateDestination(get('ID-java'),{...defaults,heritageKind:'Natural'}).hard.some(x=>x.key==='heritageKind'),false);assert.ok(evaluateDestination(get('ID-java'),{...defaults,minHighlights:50}).hard.some(x=>x.key==='minHighlights'));});

test('nearby climate reuse is transparent and restricted to an actual close reference',()=>{for(const d of destinations.filter(d=>d.climateReferenceId&&d.climateReferenceId!==d.id)){assert.ok(d.climateReferenceDistance<=25);assert.ok(climateData[d.climateReferenceId]);assert.deepEqual(d.climate.map(({daylight,...m})=>m),climateData[d.climateReferenceId].months);}});

test('retained city IDs use real city coordinates rather than distant gateway airports',()=>{const kyoto=get('JP-kyoto');assert.ok(Math.abs(kyoto.climatePoint.lat-35)<.1);assert.ok(kyoto.highlights.some(h=>h.name.includes('Kyoto')));assert.equal(destinations.filter(d=>d.type==='city'&&d.code==='JP'&&d.geoId===kyoto.geoId).length,1);});

test('confirmed match distinguishes supported interests from unresearched interests',()=>{const d=get('VN');const f={...defaults,weights:{natuur:8,wellness:2}};const result=evaluateDestination(d,f,destinations);assert.equal(result.confirmedMatch,80);assert.ok(result.unresearched.includes('wellness'));});
test('requested bands only reject known personal estimates',()=>{const d=get('VN');const f={...defaults,weights:{natuur:10},bands:{natuur:[4,9]}};assert.ok(!evaluateDestination(d,f,destinations).failures.some(x=>x.key==='band'));assert.ok(evaluateDestination({...d,scores:{natuur:2}},f,destinations).failures.some(x=>x.key==='band'));});
test('temperature can be disabled and unsafe requested countries are excluded',()=>{for(const code of ['SD','YE'])assert.ok(evaluateDestination(get(code),defaults,destinations).hard.some(x=>x.key==='excludedCountry'));assert.ok(!evaluateDestination(get('AR'),{...defaults,minTemp:60,temperatureEnabled:false},destinations).failures.some(x=>x.key==='minTemp'));});
test('Yucatan excludes its cities without excluding Mexico and Bali is unique',()=>{const all=destinations;assert.ok(get('MX-yucatan'));assert.equal(all.filter(d=>d.code==='ID'&&d.name==='Bali').length,1);const city=all.find(d=>d.parentId==='MX-yucatan'&&d.type==='city');assert.ok(city);assert.ok(excluded(city,{visitedRegions:['MX-yucatan']},all));assert.ok(!excluded(get('MX'),{visitedRegions:['MX-yucatan']},all));});
